# Generated by Django 5.0.3 on 2024-03-26 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_fname', models.CharField(max_length=70)),
                ('act_lname', models.CharField(max_length=100)),
                ('act_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dir_fname', models.CharField(max_length=70)),
                ('dir_lname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gen_tittle', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mov_title', models.CharField(max_length=100)),
                ('mov_year', models.DateField()),
                ('mov_time', models.DateTimeField()),
                ('mov_lang', models.CharField(choices=[('Ru', 'Russian'), ('En', 'English'), ('TJ', 'Tajik')], max_length=2)),
                ('mov_dt_rel', models.DateField()),
                ('mov_country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rev_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movie_cast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.actor')),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.movie')),
            ],
        ),
        migrations.CreateModel(
            name='Movie_director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dir_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.director')),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.movie')),
            ],
        ),
        migrations.CreateModel(
            name='movie_genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genres_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.genres')),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.movie')),
            ],
        ),
        migrations.CreateModel(
            name='rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rev_starts', models.IntegerField()),
                ('num_o_ratings', models.IntegerField()),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.movie')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.reviewer')),
            ],
        ),
    ]
